ccs:
  client:
    asia:
      base-url: http://localhost:${server.port}${server.servlet.context-path}
    europe:
      base-url: http://localhost:${server.port}${server.servlet.context-path}
    japan:
      base-url: http://localhost:${server.port}${server.servlet.context-path}
    vis:
      base-url: http://localhost:${server.port}${server.servlet.context-path}

spring:
  liquibase:
    change-log: classpath:/sql/changelog/db.changelog-master.yaml
  datasource:
    url: jdbc:postgresql://localhost:5020/ccs
    username: admin
    password: admin
server:
  port: 5010
  servlet:
    context-path: /car-charging-service

feign:
  client:
    config:
      default:
        connectTimeout: 1000000
        readTimeout: 1000000
        loggerLevel: basic

logging:
  level:
    root: error